Traceback (most recent call last):
  File "CreateDB.py", line 28, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '楽曲データ.csv'
Traceback (most recent call last):
  File "CreateDB.py", line 28, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '楽曲データ.csv'
Traceback (most recent call last):
  File "CreateDB.py", line 46, in <module>
  File "pandas\io\parsers\readers.py", line 1024, in read_csv
  File "pandas\io\parsers\readers.py", line 618, in _read
  File "pandas\io\parsers\readers.py", line 1618, in __init__
  File "pandas\io\parsers\readers.py", line 1878, in _make_engine
  File "pandas\io\common.py", line 873, in get_handle
FileNotFoundError: [Errno 2] No such file or directory: '楽曲データ.csv'
